config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "homeguides", to: "pages#homeguides"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :places do
    resources :guides, only: [:new, :create]
    resources :reviews, only: :create
  end

  resources :reviews, only: :destroy

  resources :guides, only: [:index, :destroy, :show, :edit, :update] do
    resources :review_guides, only: :create
  end

  resources :review_guides, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :place
  belongs_to :guide
  belongs_to :user

  validates :date, presence: true

end

app/models/guide.rb
class Guide < ApplicationRecord
  belongs_to :place
  belongs_to :user

  has_many :review_guides, dependent: :destroy
  has_many :bookings, dependent: :destroy

  has_one_attached :photo
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :guides

  belongs_to :user

  validates :place, presence: true
  validates :photo, presence: true
  validates :country, presence: true
  validates :description, presence: true, length: { minimum: 60, maximum: 1_000 }
  validates :rating, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 4 }

  has_one_attached :photo
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :place
  belongs_to :user

  validates :comment, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/review_guide.rb
class ReviewGuide < ApplicationRecord
  belongs_to :guide
  belongs_to :user

  validates :comment, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :review_guides, dependent: :destroy
  has_many :places, dependent: :destroy
  has_many :guides, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit
  before_action :configure_permitted_parameters, if: :devise_controller?

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  before_action :set_place, only: [:new, :create]
  before_action :set_guide, only: [:show, :edit, :update, :destroy]

  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @guides = policy_scope(Guide).order(created_at: :desc)
  end

  def show
    @guide.place = @place
    @review_guide = ReviewGuide.new(guide: @guide)
    authorize @guide
  end

  def new
    @guide = Guide.new
    authorize @guide
  end

  def create
    @guide = Guide.new(guide_params)
    @guide.place_id = @place.id
    @guide.user_id = current_user.id

    authorize @guide

    if @guide.save
      redirect_to guide_path(@guide)
    else
      render :new
    end
  end

  def edit
    authorize @guide
  end

  def update
    authorize @guide
    if @guide.update(guide_params)
      redirect_to guide_path(@guide)
    else
      render :edit
    end
  end

  def destroy
    authorize @guide
    @guide.destroy

    redirect_to guides_path
  end

  private

  def guide_params
    params.require(:guide).permit(:first_name, :last_name, :phone_number, :guide_name, :dni, :email, :date_of_birth, :country, :city, :age, :photo)
  end

  def set_place
    @place = Place.find(params[:place_id])
  end

  def set_guide
    @guide = Guide.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :homeguides]

  def home
    if params[:query].present?
      sql_query = " \
        places.place @@ :query \
        OR places.country :query \
        OR guides.guide_name @@ :query \
        OR guides.first_name @@ :query \
        OR guides.last_name @@ :query \
      "
      @places = Place.joins([:guide, :place]).where(sql_query, query: "%#{params[:query]}%")
    end
  end

  def homeguides
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  def index
    @places = policy_scope(Place).order(created_at: :desc)
    sql_query = " \
        places.place @@ :query \
        OR places.description @@ :query \
        OR places.country @@ :query
      "
    @places = Place.where(sql_query, query: "%#{params[:query]}%") if params[:query].present?
  end

  def show
    @review = Review.new(place: @place)
    authorize @place
  end

  def new
    @place = Place.new
    authorize @place
  end

  def create
    @place = Place.new(place_params)
    @place.user_id = current_user.id
    authorize @place
    if @place.save
      redirect_to place_path(@place)
    else
      render :new
    end
  end

  def edit
    authorize @place
  end

  def update
    authorize @place

    if @place.update(place_params)
      redirect_to place_path(@place)
    else
      render :edit
    end
  end

  def destroy
    authorize @place
    @place.destroy

    redirect_to places_path
  end

  private

  def place_params
    params.require(:place).permit(:place, :country, :description, :rating, :photo)
  end

  def set_place
    @place = Place.find(params[:id])
  end
end

app/controllers/review_guides_controller.rb
class ReviewGuidesController < ApplicationController
  def create
    @review_guide = ReviewGuide.new(review_params)
    @guide = Guide.find(params[:guide_id])
    @review_guide.guide = @guide
    @review_guide.user_id = current_user.id
    authorize @review_guide

    if @review_guide.save
      redirect_to guide_path(@guide, anchor: "review-guide-#{@review_guide.id}")
    else
      render 'guides/show'
    end
  end

  def destroy
    @review_guide = ReviewGuide.find(params[:id])
    authorize @review_guide

    @review_guide.destroy

    redirect_to guide_path(@review_guide.guide, anchor: "reviews-guide")
  end

  private

  def review_params
    params.require(:review_guide).permit(:comment, :rating)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @place = Place.find(params[:place_id])
    @review.place = @place
    @review.user_id = current_user.id
    authorize @review

    if @review.save
      redirect_to place_path(@place, anchor: "review-#{@review.id}")
    else
      render 'places/show'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    authorize @review

    @review.destroy
    redirect_to place_path(@review.place, anchor: "reviews")
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/guides/edit.html.erb
<div class="container py-5">
  <% collection = ["Argentina", "Brasil", "Bolivia", "Chile", "Perú", "Colombia", "Puerto Rico", "Costa Rica", "Mexico", "Ecuador","Guatemala", "Uruguay", "Paraguay", "Honduras", "Cuba", "El Salvador", "Nicaragua", "Panamá","Venezuela"] %>
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add place what your visit</h3>
        <%= simple_form_for [@place, @guide] do |f| %>
          <%= f.input :guide_name, placeholder: 'Enter a guide name', required: true %>
          <%= f.input :first_name, placeholder: 'Enter a first name', required: true %>
          <%= f.input :last_name, placeholder: 'Enter a last name', required: true %>
          <%= f.input :dni, placeholder: 'Enter a dni', required: true %>
          <%= f.input :age, placeholder: 'Enter a age', required: true %>
          <%= f.input :date_of_birth, as: :date, start_year: Date.today.year - 50,
                                          end_year: Date.today.year - 10, required: true %>
          <%= f.input :phone_number, placeholder: 'example +59168548541', required: true %>
          <%= f.input :email, placeholder: 'Enter a email', required: true %>
          <%= f.input :country, as: :select, collection: collection, required: true %>
          <%= f.input :city, placeholder: 'Enter a city', required: true %>
          <%= f.input :photo, as: :file, required: true %>
          <%= f.submit class: 'btn btn-outline-success' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/guides/show.html.erb
<div class="container">
  <div class="container my-4 row">
    <div class="card-guides-show rounded-2 my-3 d-inline-block col-12 col-sm-12 col-md-5 col-lg-4 col-xl-4">
      <div class="row rounded">
        <div style="background-image: url(<%= cl_image_path @guide.photo.key, height: 220 %>)" id="banner-card-profile-show" class="rounded col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4"></div>
        <div class="p-3 col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
          <h5 class="border-top pt-2"><b>Guide Username :</b></h5>
          <p><%= @guide.guide_name.capitalize %></p>
          <h5 class="border-top pt-2"><b>First Name :</b></h5>
          <p><%= @guide.first_name.capitalize %></p>
          <h5 class="border-top pt-2"><b>Last Name :</b></h5>
          <p><%= @guide.last_name.capitalize %></p>
          <h5 class="border-top pt-2"><b>Country :</b></h5>
          <p><%= @guide.country.capitalize %></p>
          <h5 class="border-top pt-2"><b>City :</b></h5>
          <p><%= @guide.city.capitalize %></p>
          <h5 class="border-top pt-2"><b>Age :</b></h5>
          <p><%= @guide.age %></p>
          <h5 class="border-top pt-2"><b>Date of Birth :</b></h5>
          <p><%= @guide.date_of_birth %></p>
          <h5 class="border-top pt-2"><b>DNI :</b></h5>
          <p><%= @guide.dni %></p>
          <h5 class="border-top pt-2"><b>Phone Number :</b></h5>
          <p><%= @guide.phone_number %></p>
          <h5 class="border-top pt-2"><b>Email :</b></h5>
          <p><%= @guide.email %></p>
        </div>
        <div class="text-center border-top col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
          <% if policy(@guide).edit? %>
            <%= link_to "Edit Profile", edit_guide_path(@guide), class: "btn btn-outline-warning mx-2 my-2" %>
          <% end %>
          <% if policy(@guide).destroy? %>
            <%= link_to "Delete Guide", guide_path(@guide), class: "btn btn-outline-danger mx-2 my-2", method: :delete, data: { confirm: "You are sure delete this profile?"} %>
          <% end %>
        </div>
        <div class="card-footer col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
          <small><em class="text-muted">Profile guide created <%= distance_of_time_in_words_to_now(@guide.created_at) %> ago</em></small>
        </div>
      </div>
    </div>
    <div class="rounded my-5 d-inline-block col-12 col-sm-12 col-md-7 col-lg-8 col-xl-8">
      <h3 class="text-center"><strong>Guide Service Information</strong></h3>
      <div class="bg-white box-shadow mx-3 my-5 container row rounded">
        <div class="border-end p-3 col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4">
          <h5 class="pt-2"><b>Cost per Hour :</b></h5>
          <p>7 $</p>
        </div>
        <div class="border-end p-3 col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4">
          <h5 class="border-top pt-2"><b>Places you Knows :</b></h5>
          <p>Samaipata, Chochis, etc.</p>
        </div>
        <div class="p-3 col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4">
          <h5 class="border-top pt-2"><b>Guide's Residence :</b></h5>
          <p>Santa Cruz de la Sierra.</p>
        </div>
        <div class="border-end p-3 col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4">
          <h5 class="border-top pt-2"><b>Minimum Service Hours :</b></h5>
          <p>2 hours for day.</p>
        </div>
        <div class="border-end p-3 col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4">
          <h5 class="border-top pt-2"><b>Maximum Service Hours :</b></h5>
          <p> hours for day.</p>
        </div>
        <div class="p-3 col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4">
          <h5 class="border-top pt-2"><b>English of the Guide :</b></h5>
          <p> Medium.</p>
        </div>
      </div>
      <hr>
      <div class="container row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
          <div class="row justify-content-center">
            <div id="reviews-guide" class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 p-4">
              <h3 class="text-shadow">Reviews</h3>
              <% if @guide.review_guides.empty? %>
                <small><em class="text-muted">Be the first one to review this place</em></small>
              <% end %>
              <% @guide.review_guides.each do |review_guide| %>
                <div>
                  <% review_guide.rating.times do %>
                    <i class="fas fa-star star-yellow"></i>
                  <% end %>
                  <small><em class="text-muted"><%= distance_of_time_in_words_to_now(review_guide.created_at) %> ago</em></small>
                  <p id="review-guide-<%= review_guide.id %>" class="mb-0 text-shadow"><%= review_guide.comment %></p>
                  <% if policy(review_guide).destroy? %>
                    <%= link_to "Delete Review", review_guide_path(review_guide), remote: true, method: :delete, class: "btn btn-outline-danger my-3", data: { confirm: "Are you sure delete place?"} %>
                  <% end %>
                </div>
                <hr>
              <% end %>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
              <div class="box-shadow bg-white rounded p-3">
                <h5 class="text-shadow">Add your review</h5>
                <%= simple_form_for([@guide, @review_guide], remote: true) do |f| %>
                  <%= f.input :comment, placeholder: "Add your review here...", required: true, class: "text-shadow" %>
                  <%= f.input :rating, as: :select, collection: (1..5), required: true, prompt: "What's your rating",  class: "text-shadow", input_html: { data: { controller: "jquery-bar-rating" } } %>
                  <%= f.submit class:"btn btn-outline-primary" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<%# cambiar las direcciones de la imagenes de la home page ya que son estaticas y no dinamicas esto puede perjudicar a que no se muestra las imagenes una vez subida a nuestro host  %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dgzbf6kp2/image/upload/v1652292241/development/home_ir0nnv.jpg);">
  <div class="container">
    <h1>Welcome to "TAG" <strong>Tourism</strong> and <strong>Guides</strong>!</h1>
    <p>Get to know the best places with local guides</p>
    <%= link_to "Go See Places", places_path, target: "_blank", class: "btn btn-outline-light" %>
  </div>
</div>
<div class="container">
  <div class="text-center my-5">
    <h2 id="font-arial" class="text-shadow"><b>TOP PLACES</b></h2>
    <p id="border-white">sssssssss</p>
  </div>
  <div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
      <div class="container-fluid">
        <div class="card-home">
          <a href="https://tag-places-sergioski9.herokuapp.com/places/1" target="_blank"><img src="https://res.cloudinary.com/dgzbf6kp2/image/upload/v1652133313/development/1yk1r6793w8pypxh9f3eaabadzua.jpg" alt="paisaje-samaipata-santa-cruz-bolivia"></a>
        </div>
        <div class="container text-center my-5">
          <h4 class="text-shadow"><b>Samaipata</b></h4>
          <p class="my-3 text-shadow">es un lugar muy bueno para pasar el rato te lo aseguro que lo pasaras bien con gente humilde de la comunidad</p>
          <div class="my-5">
            <a href="https://tag-places-sergioski9.herokuapp.com/places/1" target="_blank" class="btn-home" role="button">See More</a>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
      <div class="container-fluid">
        <div class="card-home">
          <a href="https://tag-places-sergioski9.herokuapp.com/places/2" target="_blank"><img src="https://res.cloudinary.com/dgzbf6kp2/image/upload/v1652233569/development/x22tcz81o1yov8ns1p3lhokhd5x4.jpg" alt="paisaje-chochis-santa-cruz-bolivia"></a>
        </div>
        <div class="container text-center my-5">
          <h4 class="text-shadow"><b>Chochís</b></h4>
          <p class="my-3 text-shadow">es un estupendo lugar muy bonito con artos sitios a los cuales puedes ir a visitar y pasarla bien en familia o solo</p>
          <div class="my-5">
            <a href="https://tag-places-sergioski9.herokuapp.com/places/2" target="_blank" class="btn-home" role="button">See More</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="banner mt-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dgzbf6kp2/image/upload/v1652728418/development/home-guide_grlhur.jpg);">
  <div class="container">
    <h2>Learn more about the guide service <strong>Tourism</strong> and <strong>Guides</strong>!</h1>
    <p>Find out about the guide services offered by our page</p>
    <%= link_to "Go Home Guides", homeguides_path, class: "btn btn-outline-light" %>
  </div>
</div>
<div class="container row my-5">
  <div class="container col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
    <div class="row">
      <div class="card-home my-4 col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
        <a href="https://tag-places-sergioski9.herokuapp.com/places/3" target="_blank"><img src="https://res.cloudinary.com/dgzbf6kp2/image/upload/v1652296970/development/espejillos-santa-cruz_vtqfvm.jpg" alt="espejillos-santa-cruz-bolivia" class="my-4"></a>
        <h3 class="text-center"><b>Espejillos</b></h3>
      </div>
      <div class="container-fluid col-12 col-sm-12 col-md-12 col-lg-8 col-xl-8">
        <div class="container-letters container-fluid my-5">
          <h3 class="text-shadow"><strong>Santa Cruz - Espejillos</strong></h3>
          <p class="text-shadow">Espejillos es la puerta de entrada al Parque Nacional Amboró, el lugar es un balneario formado por cascadas y saltos de agua rodeado de una vegetación selvática. Un lugar ideal para disfrutar del agua y las caminatas en medio de la naturaleza.</p>
          <p class="text-shadow">Espejillos se encuentra a 45 kilómetros de la ciudad de Santa Cruz de la Sierra. Para llegar se debe conducir por la vieja ruta a Cochabamba hasta el poblado de San José en el Municipio de Porongo, desde allí continuar por un camino bien señalizado hasta la Reserva Natural Municipal de Espejillos.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="container-fluid text-center">
    <h3 style="font-family: arial" class="text-shadow"><b>Other Amazing Places the Bolivia</b></h3>
    <div class="row justify-content-center">
      <div class="card-home mx-3 my-5 col-12 col-sm-12 col-md-12 col-lg-5 col-xl-5">
        <a href="https://tag-places-sergioski9.herokuapp.com/places/6" target="_blank"><img src="https://res.cloudinary.com/dgzbf6kp2/image/upload/v1652301803/development/m6ydloabir66kqtz74q8mqe4j9b1.jpg" alt="salar-de-uyuni-bolivia"></a>
        <h4 class="my-3 text-shadow"><b>Salar de Uyuni</b></h4>
      </div>
      <div class="card-home mx-3 my-5 col-12 col-sm-12 col-md-12 col-lg-5 col-xl-5">
        <a href="https://tag-places-sergioski9.herokuapp.com/places/7" target="_blank"><img src="https://res.cloudinary.com/dgzbf6kp2/image/upload/v1652302024/development/yfxsvwmbf0n4uxrkqtj2h4b55ewk.jpg" alt="cristo-de-la-concordia-bolivia"></a>
        <h4 class="my-3 text-shadow"><b>Cristo de la Concordia</b></h4>
      </div>
      <div class="card-home mx-3 my-5 col-12 col-sm-12 col-md-12 col-lg-5 col-xl-5">
        <a href="https://tag-places-sergioski9.herokuapp.com/places/8" target="_blank"><img src="https://res.cloudinary.com/dgzbf6kp2/image/upload/v1652302188/development/atv0b3c06762bzezv5t7ibsk6vew.jpg" alt="virgen-del-socavon-bolivia"></a>
        <h4 class="my-3 text-shadow"><b>Virgen del Socavon</b></h4>
      </div>
      <div class="card-home mx-3 my-5 col-12 col-sm-12 col-md-12 col-lg-5 col-xl-5">
        <a href="https://tag-places-sergioski9.herokuapp.com/places/9" target="_blank"><img src="https://res.cloudinary.com/dgzbf6kp2/image/upload/v1652302684/development/dfrm683wfo1ropksnqggc5c9f0h7.jpg" alt="laguna-colorada-bolivia"></a>
        <h4 class="my-3 text-shadow"><b>Laguna Colorada</b></h4>
      </div>
    </div>
  </div>
</div>

app/views/places/index.html.erb
<h2 class="text-center my-5"><b>All Places the TAG!</b></h2>

<div class="container">
  <small><em class="text-muted">Press Image for Go Place</em></small>
  <div class="row justify-content-center">
    <% @places.each do |place| %>
      <div class="my-3 col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4">
        <%= link_to place_path(place), class: "anchor-white",action: "go" do %>
          <div class="card-category rounded" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path place.photo.key, crop: :fill %>')">
            <h3 class="text-center"><b><%= place.place %></b></h3>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/places/show.html.erb
<div class="card-category-place card-large" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @place.photo.attached? ? cl_image_path(@place.photo.key) : asset_path('list_background.jpg') %>)">
  <h2><b> <%= @place.place %> - <%= @place.country %></b></h2>
</div>
<div class="row">
  <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 bg-white p-4">
    <h3 class="text-shadow"><b>Description the <%= @place.place %></b></h3>
    <p class="text-shadow"><%= @place.description %></p>
    <div class="container text-center bg-white p-4">
        <% @place.rating.to_i.times do %>
          <i class="fas fa-star star-yellow"></i>
        <% end %>
        <h4 class="d-inline-block mx-4 text-shadow"><strong>Reference Stars</strong></h4>
        <small><em class="text-muted">created <%= distance_of_time_in_words_to_now(@place.created_at) %> ago</em></small>
    </div>
    <div>
      <% if policy(@place).edit? %>
        <%= link_to "Edit Place", edit_place_path(@place), class: "btn btn-outline-warning mx-4"%>
      <% end %>
      <% if policy(@place).destroy? %>
        <%= link_to "Delete Place", place_path(@place), method: :delete, class: "btn btn-outline-danger mx-4", data: { confirm: "Are you sure delete place?"} %>
      <% end %>
    </div>
  </div>
  <hr class="">
  <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
    <div class="row justify-content-center">
      <div id="reviews" class="col-12 col-sm-6 col-md-6 col-lg-6 col-xl-5 p-4">
        <h3 class="text-shadow">Reviews</h3>
        <% if @place.reviews.empty? %>
          <small><em class="text-muted">Be the first one to review this place</em></small>
        <% end %>
        <% @place.reviews.each do |review| %>
          <div>
            <% review.rating.times do %>
              <i class="fas fa-star star-yellow"></i>
            <% end %>
            <small><em class="text-muted"><%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></small>
            <p id="review-<%= review.id %>" class="mb-0 text-shadow"><%= review.comment %></p>
            <% if policy(review).destroy? %>
              <%= link_to "Delete Review", review_path(review), remote: true, method: :delete, class: "btn btn-outline-danger my-3", data: { confirm: "Are you sure delete place?"} %>
            <% end %>
          </div>
          <hr>
        <% end %>
      </div>
      <div class="col-12 col-sm-6 col-md-6 col-lg-6 col-xl-5">
        <div class="bg-white rounded p-3">
          <h5 class="text-shadow">Add your review</h5>
          <%= simple_form_for([@place, @review], remote: true) do |f| %>
            <%= f.input :comment, placeholder: "Add your review here...", class: "text-shadow" %>
            <%= f.input :rating, as: :select, collection: (1..5), required: true, prompt: "What's your rating",  class: "text-shadow", input_html: { data: { controller: "jquery-bar-rating" } } %>
            <%= f.submit class:"btn btn-outline-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<hr class="my-3">
<div class="row">
  <div class="col-12 col-sm-12 col-md-12">
    <div class="container-fluid row">
      <h4 class="text-center text-shadow"><b>All Guides the Place</b></h4>
      <div class="my-3 text-center">
        <small><em class="text-muted">Press Image</em></small>
      </div>
      <% @place.guides.each do |guide| %>
        <div class="my-3 col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4">
          <%= link_to guide_path(guide), class: "anchor-white",action: "go" do %>
            <div class="card-category avatar-guide" style="background-image: url('<%= cl_image_path guide.photo.key, crop: :fill, height: 200, radius: :max, background: "#F4F4F4" %>')">
              <h3 class="text-center"><b><%= guide.guide_name %></b></h3>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<hr>
<div class="container row">
  <%= link_to "Create Guide Profile", new_place_guide_path(@place), class: "btn btn-outline-primary around my-4 mx-1 col-12 col-sm-5 col-md-4 col-lg-3 col-xl-3" %>
  <%= link_to "Create New Place", new_place_path, class: "btn btn-outline-primary around my-4 mx-1 col-12 col-sm-5 col-md-4 col-lg-3 col-xl-3" %>
</div>